/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './Stats';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/icon/icon';
import * as import12 from 'ionic-angular/config/config';
import * as import13 from '@angular/core/src/linker/element_ref';
var renderType_StatsPage_Host:import0.RenderComponentType = (null as any);
class _View_StatsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _StatsPage_0_4:import3.StatsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_StatsPage_Host0,renderType_StatsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('Stats',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_StatsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._StatsPage_0_4 = new import3.StatsPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._StatsPage_0_4,[],compView_0);
    compView_0.create(this._StatsPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.StatsPage) && (0 === requestNodeIndex))) { return this._StatsPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_StatsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_StatsPage_Host === (null as any))) { (renderType_StatsPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_StatsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const StatsPageNgFactory:import10.ComponentFactory<import3.StatsPage> = new import10.ComponentFactory<import3.StatsPage>('Stats',viewFactory_StatsPage_Host0,import3.StatsPage);
const styles_StatsPage:any[] = [];
var renderType_StatsPage:import0.RenderComponentType = (null as any);
class _View_StatsPage0 extends import1.AppView<import3.StatsPage> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import11.Icon;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_StatsPage0,renderType_StatsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','bar bar-header bar-light');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item-center');
    this.renderer.setElementAttribute(this._el_2,'ios','ios-bicycle');
    this.renderer.setElementAttribute(this._el_2,'md','md-bicycle');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import11.Icon(this.parentInjector.get(import12.Config),new import13.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,' \n\n',(null as any));
    this._el_5 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','row responsive-lg');
    this._text_6 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','col col-lg-6');
    this._el_8 = this.renderer.createElement(this._el_7,'h1',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'THIS IS REALLY BIG TEXT TEST',(null as any));
    this._text_10 = this.renderer.createText(this._el_5,'\n',(null as any));
    this._el_11 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col col-lg-6');
    this._el_12 = this.renderer.createElement(this._el_11,'h2',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'THIS IS REALLY BIG TEXT TEST',(null as any));
    this._text_14 = this.renderer.createText(this._el_5,'\n\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','row responsive-lg');
    this._text_17 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','col col-lg-6');
    this._el_19 = this.renderer.createElement(this._el_18,'h1',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'THIS IS REALLY BIG TEXT TEST',(null as any));
    this._text_21 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._el_22 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','col col-lg-6');
    this._el_23 = this.renderer.createElement(this._el_22,'h2',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'THIS IS REALLY BIG TEXT TEST',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n\n',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_27 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','row responsive-lg');
    this._text_28 = this.renderer.createText(this._el_27,'\n  ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','col col-lg-6');
    this._el_30 = this.renderer.createElement(this._el_29,'h1',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'THIS IS REALLY BIG TEXT TEST',(null as any));
    this._text_32 = this.renderer.createText(this._el_27,'\n',(null as any));
    this._el_33 = this.renderer.createElement(this._el_27,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','col col-lg-6');
    this._el_34 = this.renderer.createElement(this._el_33,'h2',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'THIS IS REALLY BIG TEXT TEST',(null as any));
    this._text_36 = this.renderer.createText(this._el_27,'\n\n',(null as any));
    this._text_37 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._text_38 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'ios-bicycle';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Icon_2_3.ios = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'md-bicycle';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_2_3.md = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
}
export function viewFactory_StatsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.StatsPage> {
  if ((renderType_StatsPage === (null as any))) { (renderType_StatsPage = viewUtils.createRenderComponentType('/Users/kevinisaza/node/ec0/ionic/.tmp/pages/Stats/Stats.html',0,import9.ViewEncapsulation.None,styles_StatsPage,{})); }
  return new _View_StatsPage0(viewUtils,parentInjector,declarationEl);
}